import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ClientWrapper from "./ClientWrapper";
import { LoadingProvider } from "./context/loadingContext";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"
import { MainNavbar } from "@/components/main-navbar";
import { ToastProvider } from "@/components/toast-provider";
import DarkModeToggle from "@/components/DarkModeToggle";
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

const __DEV__ = process.env.NODE_ENV

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Uscor Marketplace",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  if (__DEV__) {
    // Adds messages only in a dev environment
    loadDevMessages();
    loadErrorMessages();
  }

  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <LoadingProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative font-sans h-full`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="relative flex flex-col min-h-screen">
              <ClientWrapper>
                <ToastProvider>
                  {children}
                </ToastProvider>
              </ClientWrapper>
            </main>

            {/* <Toaster position='top-center' richColors /> */}
          </ThemeProvider>

        </body>
      </LoadingProvider>
    </html>
  );
}
